name: Create Release

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: apkg file name (use _ for space. No extension)
        required: true
      version:
        description: version string (eg. v6.1)
        required: true
        
jobs:
  create-release:
    name: ${{ github.event.inputs.file_name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: Get commit SHA
        run: echo "LAST_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create github release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ github.token }}
          file: Apkg/${{ github.event.inputs.file_name }}.apkg
          release_name: ${{ github.event.inputs.file_name }}--NoteType_${{ github.event.inputs.version }}
          tag: ${{ env.LAST_SHA }}